import { ConnectButton } from '@rainbow-me/rainbowkit';
import type { NextPage } from 'next';
import Head from 'next/head';
import styles from '../styles/Home.module.css';

import { Account } from '../components/Account'
import { Balance } from '../components/Balance'
import { Signer } from "../components/Signer"
import { SendTransaction } from '../components/SendTransaction'
import { useAccount,useBalance } from 'wagmi'

const Home: NextPage = () => {

  const { address } = useAccount()

  return (
    <div className={styles.container}>
      <Head>
        <title>RainbowKit App</title>
        <meta
          content="Generated by @rainbow-me/create-rainbowkit"
          name="description"
        />
        <link href="/favicon.ico" rel="icon" />
      </Head>

      <main className={styles.main}>
        <ConnectButton />

        <h1 className={styles.title}>
          zksync tutorial for AA Batch Transaction
        </h1>
        <Signer />

        <SendTransaction />

      </main>
    </div>
  );
};

export default Home;
